### ISSUE TITLE
Refactor rpm http layer

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#440]
Now rpm http layer uses `Rpm#batchUpdate(com.artipie.asto.Key)` to update the repository, but now we have more efficient SDK API to perform the update and sdk in asto to work with storage items and IO streams. Let's use these sdks to speed up rpm adapter. 
Also, we can extend our http api with the method to remove rpm package from repository.

**Comment by g4s8** [comment]
@olenagerasimova I think we can also add additional option to disable repository update on upload and use cron job if specified in repo config, e.g.:
```yaml
repo:
  type: rpm
  update:
    # update metadata on package upload
    on: upload
```
vs
```yaml
repo:
  type: rpm
  update:
    # update metada evey hour
    on:
      cron: "0 * * * *"
```

It could be useful for multi-instance deployments with high upload traffic.
